

package gui;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.PrintWriter;
import java.sql.*;
import javax.swing.JOptionPane;
class Window3 extends javax.swing.JFrame {

    /**
     * Creates new form Window3
     */
    public Window3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        tf_profile = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_subnet = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_gateway = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_dns1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_dns2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        activate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tf_ip = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setText("IPAddress: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(56, 105, 116, 14);
        getContentPane().add(tf_profile);
        tf_profile.setBounds(218, 76, 128, 20);

        jLabel3.setText("Subnet mask:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(56, 131, 131, 14);

        tf_subnet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_subnetActionPerformed(evt);
            }
        });
        getContentPane().add(tf_subnet);
        tf_subnet.setBounds(218, 128, 128, 20);

        jLabel4.setText("Default Gateway:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(56, 157, 131, 14);

        tf_gateway.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_gatewayActionPerformed(evt);
            }
        });
        getContentPane().add(tf_gateway);
        tf_gateway.setBounds(218, 154, 128, 20);

        jLabel5.setText("Preffered DNS Server:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(56, 189, 131, 12);

        tf_dns1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_dns1ActionPerformed(evt);
            }
        });
        getContentPane().add(tf_dns1);
        tf_dns1.setBounds(218, 185, 128, 20);

        jLabel6.setText("Alternate DNS Server: ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(57, 216, 151, 21);
        getContentPane().add(tf_dns2);
        tf_dns2.setBounds(218, 216, 128, 20);

        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(155, 314, 90, 23);

        activate.setText("ACTIVATE");
        activate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activateActionPerformed(evt);
            }
        });
        getContentPane().add(activate);
        activate.setBounds(234, 255, 90, 23);

        jLabel1.setText("get ip automatically");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(115, 33, 93, 20);

        jButton3.setText("get");
        getContentPane().add(jButton3);
        jButton3.setBounds(229, 32, 49, 23);

        jLabel8.setText("profile name:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(56, 79, 109, 14);

        tf_ip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_ipActionPerformed(evt);
            }
        });
        getContentPane().add(tf_ip);
        tf_ip.setBounds(218, 102, 128, 20);

        jButton2.setText("GO BACK");
        getContentPane().add(jButton2);
        jButton2.setBounds(94, 255, 77, 23);

        pack();
    }// </editor-fold>                        

    private void tf_subnetActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void tf_ipActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void tf_dns1ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void tf_gatewayActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void activateActionPerformed(java.awt.event.ActionEvent evt) {                                         
       String adapter_name="Wi-fi";
		String ip_address=tf_ip.getText();
		String subnet_mask=tf_subnet.getText();
		String default_gateway=tf_gateway.getText();
		String dns_1=tf_dns1.getText();
		String dns_2=tf_dns2.getText();
		String[] command =
	    {
	        "cmd",
	    };
	    Process p;
		try {
			p = Runtime.getRuntime().exec(command);
		      //  new Thread(new SyncPipe(p.getErrorStream(), System.err)).start();
	              //  new Thread(new SyncPipe(p.getInputStream(), System.out)).start();
	                PrintWriter stdin = new PrintWriter(p.getOutputStream());
	                stdin.println("netsh int ip set address "+adapter_name+" static "+ip_address+" "+subnet_mask+" "+default_gateway);
	                stdin.println("netsh int ip set dns "+adapter_name+" static "+dns_1+" primary");
	                stdin.println("netsh interface ip add dns "+adapter_name+" "+dns_2+" INDEX=2");
		                stdin.close();
	                p.waitFor();
                        
                         JOptionPane.showMessageDialog(this,"IP change successfully");
	    	} catch (Exception e) {
	 		e.printStackTrace();
		}       
    }                                        
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        try
       {
           
        
        String pn,ip,sm,gw,dns1,dns2;
        
        pn=tf_profile.getText().trim();
        ip=tf_ip.getText();
        sm=tf_subnet.getText();
        gw=tf_gateway.getText();
        dns1=tf_dns1.getText();
        dns2=tf_dns2.getText();
        
        Class.forName("com.mysql.jdbc.Driver");
            System.out.println("driver loaded successfully");
            Connection conn
                    = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/ipam", "root", "system");
            System.out.println("connection built");
            Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            System.out.println("statement created");
            
            ResultSet rs = stmt.executeQuery("select * from profile where profile_name=" + tf_profile);
            System.out.println("ResultSet Created");
            //////////////
            
            if (rs.next())      // if 1 row is fetched
            {
                System.out.println("-- This profile already exists --");
            }
            else               // if no row is fetched 
            {
                rs.moveToInsertRow();
                
                rs.updateString("profile_name", pn);
                //rs.updateString("username", name1);
                rs.updateString("ip", ip);
                rs.updateString("subnet", sm);
                rs.updateString("gateway", gw);
                rs.updateString("dns1", dns1);
                rs.updateString("dns2", dns2);
                
                rs.insertRow();
                System.out.println("*** Record Added ***");
            }
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton activate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField tf_dns1;
    private javax.swing.JTextField tf_dns2;
    private javax.swing.JTextField tf_gateway;
    private javax.swing.JTextField tf_ip;
    private javax.swing.JTextField tf_profile;
    private javax.swing.JTextField tf_subnet;
    // End of variables declaration                   

    
    //public void actionPerformed(ActionEvent e) {
        //
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    //}
}
